name: "Spawn XML Feeds"

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  schedule:
    - cron:  '0 9 * * *'


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.ASCS }}

    steps:
    - uses: actions/checkout@v2

    - name: Install Python tools
      run: sudo apt-get update && sudo apt-get -y install python3 python3-venv

    - name: Get Python version
      run: python3 --version

    - name: List contents of the current folder
      run: ls

    - name: Create virtual environment
      run: cd src && python3 -m venv env

    - name: List contents of the current folder
      run: ls src

    - name: Process dependencies & update feeds
      run: source src/env/bin/activate && pip install -r src/feedingress/requirements.txt && cd src && python -m feedingress

    - name: Run the feed ingress
      run: cd src && python -m feedingress
