name: "Validate random papers feed"

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

env:
  FEED_HOST: ${{ vars.R2_DEV_BUCKET_URL}}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.os }}

    steps:
      - name: set env
        run: |
          echo "FEED_URL=${FEED_HOST}/random-last-week.xml" >> $GITHUB_ENV
      - uses: dend/actions/rss-validator@master
